import main


class TestDoc(main.TestWebsite):
    # def test_upload_doc_with_click(self):
    #     self.reg_and_log_object("uname").send_keys("ditest10@tandatanganku.com" + self.keys.ENTER)
    #     self.reg_and_log_object("password").send_keys("Coba1234" + self.keys.ENTER)
    #     main.delay(2)
    #     self.reg_and_log_object("btn_input_file").click()
    #     self.driver.find_element(self.by.XPATH, "//body").send_keys(self.keys.ENTER)
    #     # self.reg_and_log_object("doc_file").send_keys(
    #     #     "C:\\Users\\dignitas\\Downloads\\company_image_20221101065745 (1) (1).pdf")
    #     # self.reg_and_log_object("doc_submit").click()
    #     main.delay(4)

    def test_pertama(self):
        self.reg_and_log_object("uname").send_keys("ditest10@tandatanganku.com" + self.keys.ENTER)
        self.reg_and_log_object("password").send_keys("Coba1234")
        self.reg_and_log_object("password_submit").click()
        main.delay(2)
        self.document_object("need_sign").click()
        main.delay(1)
        self.document_object("check_doc1").click()
        self.document_object("check_doc2").click()
        self.document_object("sign_all_btn").click()
        self.document_object("proses_btn").click()
        self.document_object("otp_email").click()
        main.delay(25)
        self.document_object("proses_doc_btn_submit").click()
        main.delay(3)
        self.document_object("yakin_btn").click()
        main.delay(3)
        self.document_object("btn_selesai").click()
        main.delay(5)

    def test_kotak_masuk(self):
        self.reg_and_log_object("uname").send_keys("ditest10@tandatanganku.com" + self.keys.ENTER)
        self.reg_and_log_object("password").send_keys("Coba1234" + self.keys.ENTER)
        main.delay(2)
        self.document_object("nav_inbox").click()
        self.document_object("kotak_masuk").click()
        main.select_option(self.document_object("filter_action")).select_by_visible_text("Need Action")
        self.document_object("filter_submit").click()
        main.delay(1)
        self.document_object("check_doc3").click()
        self.document_object("check_doc4").click()
        self.document_object("sign_all_btn").click()
        self.document_object("proses_btn").click()
        self.document_object("otp_email").click()
        main.delay(25)
        self.document_object("proses_doc_btn_submit").click()
        main.delay(3)
        self.document_object("yakin_btn").click()
        main.delay(3)
        self.document_object("btn_selesai").click()
        main.delay(5)
